[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm[toml]>=7.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ner-in-docker"
dynamic = ["version"]
description = ""
license = { file = "LICENSE" }
authors = [{ name = "HURIDOCS" }]
requires-python = ">= 3.10"
dependencies = [
    "fastapi==0.115.6",
    "python-multipart==0.0.20",
    "cmake==3.31.6",
    "pydantic==2.12.1",
    "gunicorn==23.0.0",
    "uvicorn==0.34.0",
    "flair==0.15.1",
    "gliner==0.2.15",
    "spacy==3.8.7",
    "dateparser==1.2.0",
    "Unidecode==1.3.8",
    "RapidFuzz==3.11.0",
    "country_converter==1.3",
    "huggingface-hub==0.27.1",
    "requests==2.32.5",
    "torch==2.7.1",
    "pdf-annotate==0.12.0"
]

[project.urls]
HURIDOCS = "https://huridocs.org"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
write_to = "_version.py"